print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/jonathanodgis/Sonic-The-Hedgehog-Controller-Unity/Sonic The Hedgehog Unity/Assets/Models/sonic_cd_level_draft_a.mb"`)
{		
	file -o "/Users/jonathanodgis/Sonic-The-Hedgehog-Controller-Unity/Sonic The Hedgehog Unity/Assets/Models/sonic_cd_level_draft_a.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/jonathanodgis/Sonic-The-Hedgehog-Controller-Unity/Sonic The Hedgehog Unity/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";

sysFile -delete "/Users/jonathanodgis/Sonic-The-Hedgehog-Controller-Unity/Sonic The Hedgehog Unity/Temp/CommandPipe";

$donepipeKill = `fopen "/Users/jonathanodgis/Sonic-The-Hedgehog-Controller-Unity/Sonic The Hedgehog Unity/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
